FROM ruby:3.4.8-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      curl \
      libyaml-dev \
      pkg-config \
      libjemalloc2 \
      libvips \
      sqlite3 \
      libsqlite3-dev && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="" \
    BUNDLE_DEPLOYMENT=""

COPY Gemfile Gemfile.lock vendor ./

RUN bundle install

COPY . .

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
